config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lessons
  root 'lessons#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.create(lesson_params)
    redirect_to lessons_path
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    @lesson.update(lesson_params)
    redirect_to lesson_path(params[:id])
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    if @lesson.destroy
      flash[:notice] = 'Lesson deleted'
      redirect_to lessons_path
    else
      flash[:notice] = 'There was a problem with deleting this'
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :lesson, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatIDid</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/all_lessons.html.erb
<% if @lessons.any? %>
  <% @lessons.each do |l|%>
    <h2><%= l.title %></h2>
    <p><%= l.lesson %></p>
    <p><%= link_to l.title, lesson_path(l.id) %></p>
  <% end %>
<% else%>
  <p><%="There are no lessons"%></p>
<% end %>

app/views/lessons/edit.html.erb
<%= form_for @lesson do |l|  %>
  <%= l.label :title %>
  <%= l.text_field :title %>
  <%= l.label :lesson %>
  <%= l.text_field :lesson %>
  <%= l.submit %>
<% end %>

app/views/lessons/index.html.erb
<h1><%="Welcome to lessons"%></h1>

<% if @lessons.any? %>
  <% @lessons.each do |l| %>
    <h2><%= l.title %></h2>
    <p><%= link_to l.title, lesson_path(l.id) %></p>
  <% end %>
<% else%>
  <p><%="There are no lessons"%></p>
<% end %>

<a href= '/lessons/new'> Add a lesson </a>

app/views/lessons/new.html.erb
<h1><%= "This is where lessons get made" %> </h1>

<%= form_for @lesson do |l|  %>
  <%= l.label :title %>
  <%= l.text_field :title %>
  <%= l.label :lesson %>
  <%= l.text_field :lesson %>
  <%= "Please upload your screen print" %>
  <%= l.file_field :avatar %>
  <%= l.submit %>
<% end %>

app/views/lessons/show.html.erb
<h1><%="Here are is the lesson #{@lesson.title}"%></h1>
<p><%= @lesson.lesson %></p>
<%= image_tag @lesson.avatar.url %>
<%= link_to 'Delete this lesson', lesson_path(@lesson), method: :delete%>
<%= link_to 'Edit this lesson', edit_lesson_path(@lesson) %>
<a href= '/'> Back to the begining </a>